#
# Makefile for homework submissions
# 
submit:
	@cp -i hw4.c /home/zhuang/dropbox/hw4/hw4-`whoami`.c && echo "`date`: hw4 submitted successfully" || echo "`date`: hw4 failed to be submitted, please try again"
