#
# Makefile for homework submissions
# 
submit:
	@cp -i hw2.c /home/zhuang/dropbox/hw2/hw2-`whoami`.c && echo "`date`: hw2 submitted successfully" || echo "`date`: hw2 failed to be submitted, please try again"
