#
# Makefile for homework submissions
# 
submit:
	@cp -i hw3.c /home/zhuang/dropbox/hw3/hw3-`whoami`.c && echo "`date`: hw3 submitted successfully" || echo "`date`: hw3 failed to be submitted, please try again"
